development:
  projectmill_path: '$HOME/Projects/ecoplotter/projectmill'
  tilemill_path: '/usr/share/tilemill'

test:
  projectmill_path: '$HOME/Projects/ecoplotter/projectmill'
  tilemill_path: '/usr/share/tilemill'

production:
  projectmill_path: '$HOME/mapbox/projectmill'
  tilemill_path: '/usr/share/tilemill'
