development:
  adapter: postgis
  database: bluecarbon_development
  pool: 5
  username: postgres
  password:
  host: localhost
  template: template_postgis

test:
  adapter: postgis
  database: bluecarbon_test
  host: localhost
  pool: 5
  username: postgres
  password:
  host: localhost
  template: template_postgis

production:
  adapter: postgresql
  database: bluecarbon_production
  host: localhost
